### ISSUE TITLE
meta: Project future?

### ISSUE THREAD

**Issue by pfalcon** [decomp/decomp#169] opened 2015-05-24 23:04 UTC
Ok, turns out this was you thesis project. Great, thanks for recording here each step you made, etc. But what's next? Most students give up on their projects when they graduate and hit real world, need to look for a job, then do that job, etc. What are your plans regarding the project and its maintenance?

**Comment by mewmew** [comment] 2015-05-25 00:47
Hi Paul,

I know that this is the unfortunate fate of many student dissertation projects. That being said, my friends and I have a genuine interest in developing a high-quality open source decompiler and have been brainstorming and discussing design ideas long before the dissertation started. Making this my final year project was simply an excuse to finally get time to start developing! We have every intention of continuing to develop this project, and want to turn it into a true open source project. While we have contributed to other open source projects in the past, this is the first time we try to get members from the open source community to join one of our projects. And, as you've already pointed out in #168, collaboration is _fundamental_ to start tackling the interesting problems of decompilation:

>  But now seeing you and bunch other people having the same "fun", all I see is **great** waste of effort. We're drowned in trivialities like "control flow graph generation" and never can reach "stumbling blocks" aka really interesting, challenging stuff.

More concretely, the future work we have anticipated is outlined in section 10.2 (Future Work). It will of cause be subject to changes as we learn more about how the decompilation pipeline will look like. One thing is for sure though, it will always be composed of small specialized tools with well-defined input/output, as advocated by the UNIX philosophy. This solves one of the issues you've already pointed out in issue #168, how to make tools work together when they are developed in different languages. Each tool will considered a black box (that may be implemented in any language), which operate purely on well-defined input and output (e.g. [LLVM IR input](https://raw.githubusercontent.com/decomp/ll2dot/master/testdata/for.ll) -> [control flow graph in the Graphviz DOT format](https://raw.githubusercontent.com/decomp/ll2dot/master/testdata/for_graphs/main.dot)). No language specific details may ever leak through the abstract components.

For reference, I've included section 10.2 below:

# Future Work

The primary focus for planned future work is to stress test the design of the decompilation pipeline and its individual components. A secondary focus is to improve the quality and the reliability of the components. A tertiary focus is to extend the capabilities of the decompilation pipeline. This prioritization strives to validate the core of the system before extending it.

## Design Validation

The principle of separation of concern has influenced every aspect of the design of the decompilation pipeline and its individual components. Conceptually, the components of the decompilation pipeline are grouped into three modules which separate concerns regarding the source language (front-end module), the general decompilation tasks (middle-end module), and the target language (back-end module). This conceptual separation is a vital aspect of the decompilation pipeline design, and it will therefore be thoroughly examined. Should a component violate the principle of separation of concern, either in isolation or within the system as a whole, it must be redesigned or reimplemented. To identify such issues, key areas of the decompilation pipeline will be extended to put pressure on the design.

Firstly, an additional back-end (e.g. support for Python as a target language) will be implemented to put pressure on the design of the middle-end module. The second back-end would only be able to leverage the target-independent information of the general decompilation tasks (e.g. control flow analysis) if the middle-end module was implemented correctly.

Secondly, a key component (e.g. data flow analysis) will be implemented in a separate programming language (e.g. Haskell, Rust, Prolog, …) to validate the language-agnostic aspects of the design. This component would only be able to interact with the rest of the decompilation pipeline, through well-defined input and output (e.g. LLVM IR, JSON, DOT, …), if the other components were implemented correctly.

The separation of the front-end and the middle-end has already been validated. These modules are only interacting through an intermediate representation (i.e. LLVM IR), and a variety of source languages are already supported by the front-end module which consists of components from several independent open source project (e.g. Dagger, Fracture, MC-Semantic, Clang, …).

The design of the control flow analysis component has both advantages and limitations, as discussed in section 6.3.2. The most significant limitation is the lack of support for control flow primitives with a variable number of nodes in their graph representations (e.g. n-way conditionals). To gain a better understanding of this issue, an analysis of control flow primitives from different high-level languages will be conducted. Should the n-node control flow primitives prove to be rare, hard-coded support for n-way conditionals (e.g. `switch`-statements) and similar control flow primitives would suffice. Otherwise, a general solution to the problem will be required (such as the introduction of a domain specific language which describes dynamic properties of the nodes and edges in DOT files). The OpenCL decompiler presented by S. Moll solved this problem by converting n-way conditionals into sets of 2-way conditionals [10].

As described in section 9.2, the current implementation of the control flow analysis component enforces a single-entry/single-exit invariant on the graph representations of high-level control flow primitives. This invariant prevents the recovery of infinite loops, as their graph representation has no exit node. At this stage it is unclear whether a refined implementation may relax the invariant to support single-entry/no-exit graphs, or if the limitation is inherent to the design. This issue requires further investigation before a potential solution may be proposed.

## Reliability Improvements

As described in section 7.3, there are many reliability issues caused by the Go bindings for LLVM. To mitigate these issues a pure Go library is being developed for interacting with LLVM IR (see section 7.2). This library will be reusable by other projects, and the requirements of the third-party Go compiler [`llgo`](https://llvm.org/svn/llvm-project/llgo/trunk/README.TXT) are actively being [tracked](https://github.com/llir/llvm/issues/3).

To ensure reliable interoperability between components written in different programming languages, the intermediate representation (i.e. LLVM IR) of the decompilation pipeline must be well-defined. Previous efforts to produce a formal grammar for LLVM IR have only focused on subsets of the language (as mentioned in section 5.1), and no such grammar has been officially endorsed. Producing an official formal specification for LLVM IR would require huge efforts, but it would enable interesting opportunities. For instance, with a formal grammar it would be possible to create a tool which automatically generates grammatically correct LLVM IR assembly which may be used to verify the various implementation of LLVM IR. This approach has been used by the GoSmith tool to generate random, but legal, Go programs which have uncovered 31 bugs in the official Go compiler, 18 bugs in the Gccgo compiler, 5 bugs in the `llgo` compiler, and 3 bugs in the Go language specification [44].

## Extended Capabilities

The official Go compiler was automatically translated from C to Go in preparation for the 1.5 release (to be released in August 2015) [45]. To make the C-style Go source code more idiomatic, Russ Cox wrote a tool called [`grind`](https://github.com/rsc/grind) which moves variable declarations closer to their usage. This tool is a perfect fit for the decompilation pipeline, and may be used as-is to extend the post-processing stage of the Go back-end.

In the far future, a type analysis component will be implement to support type recovery during decompilation. As type analysis requires type constraints equations to be solved, the component will be implemented in a language with good support support for constraints programming (e.g. Prolog). At this stage, more research is required to determine how generic type inference algorithms (e.g. Algorithm W [46]) may influence the design.

**Comment by mewmew** [comment] 2015-05-25 00:59
> Firstly, an additional back-end (e.g. support for Python as a target language) will be implemented to put pressure on the design of the middle-end module. The second back-end would only be able to leverage the target-independent information of the general decompilation tasks (e.g. control flow analysis) if the middle-end module was implemented correctly.

If you could help us flesh out a Python back-end that would be simply amazing! I know this is a semi-large/large task, but the whole purpose of the decompilation pipeline is to make the implementation of additional back-ends as simple as possible, by dealing with general decompilation tasks in the middle-end module (which currently handles Control Flow Recovery using `ll2dot` and `restructure`). The Python back-end would heavily stress test the separation of concerns principle which is fundamental to the design of the entire decompilation pipeline. Even if you decide that implementing a Python back-end would be too time consuming for you at this point, I would be very interested in discussing with you how such a back-end may be implemented, as you are by far the most experienced Python programmer of our team so far :)

**Comment by mewmew** [comment] 2015-05-25 01:02
Please note that Data Flow Analysis will be covered by the middle-end module in the future, so you don't need to (and shouldn't) implement expression propagation in the back-end.

The Go back-end uses a post-processing stage which performs expression propagation (using the _localid_ rewrite rule of `go-post`). This code will be removed as soon as the middle-end gain proper support for Data Flow Analysis.

**Comment by mewmew** [comment] 2015-05-25 01:26
More specifically, a Python back-end would currently need to perform lazy translation (i.e. unoptimized translation, no expression propagation, etc.) of individual LLVM IR instructions (e.g. `%4 = add i32 %sum, %i`) to Python statements (e.g. `_4 = sum + i`) while incorporating the high-level control flow information produced by the `restructure` tool. An example is provided below:

INPUT ([foo.ll](https://raw.githubusercontent.com/decomp/decompilation/master/poster/demo/foo.ll)):

``` llvm
; ModuleID = 'foo.ll'
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nounwind uwtable
define i32 @main(i32 %argc, i8** %argv) #0 {
  br label %1

; <label>:1                                       ; preds = %9, %0
  %i.0 = phi i32 [ 0, %0 ], [ %10, %9 ]
  %x.0 = phi i32 [ 0, %0 ], [ %x.1, %9 ]
  %2 = icmp slt i32 %i.0, 10
  br i1 %2, label %3, label %11

; <label>:3                                       ; preds = %1
  %4 = icmp slt i32 %x.0, 100
  br i1 %4, label %5, label %8

; <label>:5                                       ; preds = %3
  %6 = mul nsw i32 3, %i.0
  %7 = add nsw i32 %x.0, %6
  br label %8

; <label>:8                                       ; preds = %5, %3
  %x.1 = phi i32 [ %7, %5 ], [ %x.0, %3 ]
  br label %9

; <label>:9                                       ; preds = %8
  %10 = add nsw i32 %i.0, 1
  br label %1

; <label>:11                                      ; preds = %1
  ret i32 %x.0
}

attributes #0 = { nounwind uwtable "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.ident = !{!0}

!0 = !{!"clang version 3.6.0 (tags/RELEASE_360/final)"}
```

INPUT ([main.json](https://raw.githubusercontent.com/decomp/decompilation/master/poster/demo/foo_graphs/main.json)):

``` json
[
    {
        "prim": "list",
        "node": "list0",
        "nodes": {
            "A": "8",
            "B": "9"
        }
    },
    {
        "prim": "if",
        "node": "if0",
        "nodes": {
            "A": "3",
            "B": "5",
            "C": "list0"
        }
    },
    {
        "prim": "pre_loop",
        "node": "pre_loop0",
        "nodes": {
            "A": "1",
            "B": "if0",
            "C": "11"
        }
    },
    {
        "prim": "list",
        "node": "list0",
        "nodes": {
            "A": "0",
            "B": "pre_loop0"
        }
    }
]
```

EXAMPLE OUTPUT `foo.py`:

``` py
def main():
    i_0 = 0
    x_0 = 0
    while True:
        _2 = i_0 < 10
        if not _2:
            break
        _4 = x_0 < 100
        x_1 = x_0
        if _4:
            _6 = 3 * i_0
            _7 = x_0 + _6
            x_1 = _7
        _10 = i_0 + 1
        i_0 = _10
        x_0 = x_1
    exit(x_0)

main()
```

**Comment by pfalcon** [comment] 2015-05-25 08:46
> For reference, I've included section 10.2 below:

I got it, I got it, you want me to read your thesis before I (re)read Cifuentes' and Van Emmerik's theses I already have in queue ;-). I'll try to do it.

**Comment by pfalcon** [comment] 2015-05-25 08:58
> If you could help us flesh out a Python back-end that would be simply amazing!

Well, I may imagine why Go was chosen as decompilation target language for your work - to stay within same language domain. It's a weird choice for decompilation of machine code though - it doesn't have real pointers, and that's essence of how standard CPUs work. But Python is even weirder choice for target language, I for one see no practical use in that. I really suggest Python as an implementation language, due to its clarity, popularity, strict-typedness, but the only viable choice for decompilation target language is C, maybe C++ if you really want to decompile "object-oriented" apps.

**Comment by pfalcon** [comment] 2015-05-25 09:24
> That being said, my friends and I have a genuine interest in developing a high-quality open source decompiler and have been brainstorming and discussing design ideas long before the dissertation started.

Nice to hear. To give a counter-example (and clarify my decompilation interest and why I'm going to disappear soon), last student project I found really interesting was https://github.com/fpw/kianxali . I even contributed some patching to it, but the original author didn't really develop it further. And if continuing it myself, I faced number of unfavorable (for me) choices: Java, a verbose compiled language, a GUI framework with as usual buggy and needs workarounds, Ruby as builtin scripting instead of Python. In the end, I decided that reimplementing such tool from scratch in "right" way will be easier, and started https://github.com/pfalcon/ScratchABit . My excursion into decompilation is getaway from a normal development course of it (which is no science, just grunt coding work, and I prefer to err on scientific side of things).

Well, I already saw all what I wanted to saw - decompilation isn't as hard as can be seen from a lot of quarter-finished projects - I can have a progress beyond many projects in 2-3 work sessions, even without re-reading materials I read years ago. But it's definitely hard enough to get useful results even for simplish real-world cases (see graph in #172). The last thing I want to try before getting back to real-world tasks is recovering generalized loops (i.e. with break/continue, which are not structured control flow in some formal definitions of it, but very structured from human point of view, so let's call them semi-structured). Note that declarative subgraph matching like you use isn't going to work for that at all (it's not structured CF in the sense that it doesn't produce static CFG patterns), so algorithmic matching is required.

**Comment by mewmew** [comment] 2015-05-25 10:27
> Well, I may imagine why Go was chosen as decompilation target language for your work - to stay within same language domain. It's a weird choice for decompilation of machine code though - it doesn't have real pointers, and that's essence of how standard CPUs work.

It is true that Go has no pointer arithmetic, unless using package [unsafe](https://golang.org/pkg/unsafe/). That being said, I do believe a lot of code may be decompiled into higher-level languages using proper Data Flow Analysis and Type Analysis. Once structures and user defined types have been recovered, a lot of the pointer arithmetic may be translated to higher-level abstractions, e.g. field access in struct, element access of slice, and so on. It is definitely true that there will exist code which cannot be decompiled in this way, and for those cases it may be possible to use [cgo](https://golang.org/cmd/cgo/) and even [Assembly](https://golang.org/doc/asm).

> But Python is even weirder choice for target language, I for one see no practical use in that. I really suggest Python as an implementation language, due to its clarity, popularity, strict-typedness, but the only viable choice for decompilation target language is C, maybe C++ if you really want to decompile "object-oriented" apps.

The [Retargetable decompiler](https://retdec.com/) (which also uses LLVM IR for decompilation) already supports Python as an output language, along side of C. I completely agree that the higher-level language you try to translate into, the more difficult it will become. At the same time, I think this is what makes it interesting! Translating Assembly into C (often referred to as _portable assembly_) is an amazing endeavour, and it will certainly facilitate reverse engineering efforts. However, other projects have been doing this for years, and while I am new to the practice of developing decompilers, I would much rather experiment with something that is out of my league and most likely fail, than to not try at all. I forgot who said it, but _doing what has never been done before is intellectually stimulating_, as you would probably agree.

**Comment by mewmew** [comment] 2015-05-25 10:38
Just to clarify, a C back-end will of cause be added to the decompilation pipeline in the future. And it is quite likely, that this back-end will be the most capable of them all. That being said, I see huge benefits of enabling users to decompile _selected_ functions into higher level languages, as the whole purpose of decompilation is to facilitate understanding and enable new use cases.

**Comment by mewmew** [comment] 2015-05-25 10:49
> To give a counter-example (and clarify my decompilation interest and why I'm going to disappear soon)

We both know that there is nothing I can say to convince you that this project will be _different from all the others_™. I also know that I would be sad to see you leave, but fully understand if you decided to make an excursion into decompilation simply for the challenge of it, and when it stops being challenging you go back to other endeavours. For what it's worth, I have missed these kinds of discussions. As you already pointed out in issue #168, finding people to discuss these topics with is not trivial.

> when I was working on "compiler" part (llvm-codegen-py), I wished I could go and ask someone something. But there're very few compiler projects, and I wondered if there's a mailing list for that (to clarify, not to generic compiler stuff like parsing, which is boring topic, but "codegeneration" part)

**Comment by mewmew** [comment] 2019-01-30 19:19
Closing this meta issue for new. The project continues, at the same slow and steady pace as always. The rough roadmap is as follows.

Spring 2019.
* Add Cifuences' Interval method to `cmd/restructure` to improve control flow recovery.

Autumn 2019
* Look into binary lifting.

2020-
* The future will tell :)

**Closed as completed by mewmew** 2019-01-30 19:19 UTC
Labels: meta
